name: server

services:
  pg:
    image: bitnami/postgresql:13.16.0
    ports: 
      - "4420:5432"
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=GoalTrack